### ISSUE TITLE
Fix/improve potential issues in schedule xml

### ISSUE THREAD

**Issue by smit1678** [hotosm/hot-summit-2019#14]
Feedback on first iteration: 

> * “guid” value for all events is the same, while is should be unique. If you’re generating it by hand, the shortcut would be to use strfprint("385033fe-dda1-555a-aca6-28dd05677c%02d”, event.id) — or whatever language you use, you should get the idea.
> * day.start and day.end do not have time zone, and I think they should. Just add “+02:00”, as the sotm schedule does.
> * room names are shortened, and they should not be. “West Lecture Room” instead of “westlecture” and so on.
> * event/start is in am/pm format, and it should not be: “09:00” instead of “9:00 AM”.
> * event/duration is a floating point number, and it should be a time: “00:45” instead of “45.0”.
> * conference/timeslot_duration is a grid size: number of minutes every talk duration is divisible by. In your case it might be “00:15”.
> * coffee breaks usually are not added to schedules, but if you want to, please format these like other talks, with proper durations at least and inside the “Main Lobby” room.
> * when there are no persons associated with an event, just keep the list empty — please do not add a person with id=0.
> * where there are speakers, please make unique ids for them, possibly by incrementing a number.

**Comment by dakotabenjamin** [comment]
questions: 
- How do you want to format the GUID? I can made it iterate that long string as suggested above or we could simplify it. 
- Do we need an ID for persons? do the IDs have to be consistent (ie. jess b.  has the same ID across the document)?
- Is the coffee break on the 20th at 10:30 actually in the West Lecture Room or the Lobby?

**Comment by dakotabenjamin** [comment]
addendum to the presenter IDs:
 - do we want to iterate from 0 for the whole document, or within the `<persons>` tag only? ie.

option 1:
```
<persons>
    <person id="0">Jess Beutler</person>
    <person id="1">Geoffrey Kateregga</person>
</persons>
.
.
.
<persons>
    <person id="2">Catalina Jaime</person>
    <person id="3">Stefan Scholtz</person>
</persons>
```

option 2:
```
<persons>
    <person id="0">Jess Beutler</person>
    <person id="1">Geoffrey Kateregga</person>
</persons>
.
.
.
<persons>
    <person id="0">Catalina Jaime</person>
    <person id="1">Stefan Scholtz</person>
</persons>
```
