### ISSUE TITLE
Sponsor Logos to Summit.hotosm.org

### ISSUE THREAD

**Issue by vannicer** [hotosm/hot-summit-2019#2]
We need the following logos added to the main page for Summit.hotosm.org at the following levels: 
Platinum: AWS
Gold: Facebook, Grab
Silver: Mapbox, ESRI-Germany

Let me know where I can save/upload logos for easy use

**Comment by vannicer** [comment]
Add Microsoft logo to Gold

**Comment by smit1678** [comment]
done
