### ISSUE TITLE
Add Location Links

### ISSUE THREAD

**Issue by vannicer** [hotosm/hot-summit-2019#25]
Locations for each location here- https://drive.google.com/open?id=1Vh-Yuo-fgn027Y6DZFmr058smv_pvGpse4dlAVYLJXg

Would like in-text links on Program page, if possible

**Comment by smit1678** [comment]
@vannicer Already added and just waiting for a thumbs up and merge from @dakotabenjamin: https://github.com/hotosm/hot-summit-2019/pull/26

**Comment by smit1678** [comment]
Done and live!
