### ISSUE TITLE
Mobile nav not clickable 

### ISSUE THREAD

**Issue by smit1678** [hotosm/hot-summit-2019#30]
The mobile nav is not clickable. There do not seem to be any javascript errors plus the nav works on desktop view so not sure the issue. Seen on both Chrome and Firefox. 

<img width="497" alt="HOT Summit 2019 | Program 2019-09-03 11-23-31" src="https://user-images.githubusercontent.com/796838/64144250-db5ad200-ce3d-11e9-8475-b92e8058fa25.png">

cc @dakotabenjamin

**Comment by dakotabenjamin** [comment]
I'm not able to replicate this. Can you provide any more info? 
I tried on Pixel 2 Chrome and Firefox
and on Chrome on Ubuntu using Developer tools

**Comment by smit1678** [comment]
Ok, interesting this is on iOS 12.4.1 on both Firefox, Chrome, and Safari browsers. I didn't clarify here though -- it works on landing page. It's just the Program page: https://summit2019.hotosm.org/program/

**Comment by dakotabenjamin** [comment]
Fixed via #31
