### ISSUE TITLE
Change room names in program

### ISSUE THREAD

**Issue by vannicer** [hotosm/hot-summit-2019#34]
Change West Lecture to Horsaal West,  East Lecture to Horsaal Ost, & Small Lecture to Kleiner Horsaal

**Comment by dakotabenjamin** [comment]
@vannicer do you want `Horsaal West` or `Horsaal West Room` etc.?

**Comment by vannicer** [comment]
Hey Dakota, either is fine. ‘Horsaal’ is Lecture Hall in German, so I just wanted something recognizable for participants, because it’s written over the doors. If it’s not up stick with Horsaal West, etc. if you’ve already added “room” that’s totally fine as well. Thanks!!

**Comment by smit1678** [comment]
Done!
