### ISSUE TITLE
Add speakers page

### ISSUE THREAD

**Issue by smit1678** [hotosm/hot-summit-2019#8]

**Comment by smit1678** [comment]
A rough draft of the speaker page going here in #17: 

![image](https://user-images.githubusercontent.com/796838/63079991-1322d800-bf6a-11e9-9730-5b2d4dc27f73.png)

**Comment by hexiaok** [comment]
<img width="1680" alt="Screen Shot 2019-08-21 at 10 36 42 PM" src="https://user-images.githubusercontent.com/26889634/63441585-3e269380-c464-11e9-83fc-12d7020bd14a.png">
play with some CSS. i don't think we need to apply color to the speaker organization or location. just use #68707F or #929DB3
I also change the intro paragraph to black color. now the page is super red 
then for the talk title we can use red and i assume it will link somewhere?
btw, can we remove the side session"contact summit working group"? then we can expand the card and have more space for the text @smit1678

**Comment by smit1678** [comment]
@hexiaok Yeah we could remove, here's what removing plus making the speakers four cards wide:

<img width="1435" alt="HOT Summit 2019 | Speakers 2019-08-30 10-48-14" src="https://user-images.githubusercontent.com/796838/63989678-cddada80-cb13-11e9-943a-787e4cf515d4.png">

**Comment by smit1678** [comment]
Switched to wider view 👍 Going to close this unless there are other things to hit @hexiaok?
